# ?????SQL???????????????JPA?ddl-auto???
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.encoding=UTF-8

# ??JPA?????????SQL????????
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update

# ??H2?????????????
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:${user.dir}/h2-db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=123456

# H2?????????????????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


server.port=8080
server.servlet.context-path=/demo

logging.charset.console=UTF-8
logging.charset.file=UTF-8

# ??Spring Boot???ANSI??????????
spring.output.ansi.enabled=NEVER
#spring.output.ansi.enabled=ALWAYS


jwt.secret=${JWT_SECRET:javaDemoSecretKey1234567890abcdefghijklmn}

jwt.expire=3600000